-- Skrypt usuwający wszystkie utworzone tabele --
DROP table IF EXISTS osoby CASCADE;
DROP table IF EXISTS uslugodawcy CASCADE;
DROP table IF EXISTS personel_medyczny CASCADE;
DROP table IF EXISTS zatrudnieni CASCADE;
DROP table IF EXISTS specjalizacje CASCADE;
DROP table IF EXISTS typy_uslug CASCADE;
DROP table IF EXISTS uslugi CASCADE;
DROP table IF EXISTS oddzialy CASCADE;
DROP table IF EXISTS apteki CASCADE;
DROP table IF EXISTS recepty CASCADE;
DROP table IF EXISTS leki CASCADE;
DROP table IF EXISTS choroby CASCADE;
DROP table IF EXISTS recepta_lek CASCADE;
DROP table IF EXISTS zgloszenie CASCADE;
DROP table IF EXISTS umowy CASCADE;
DROP table IF EXISTS historia_chorob CASCADE;
DROP table IF EXISTS zatrunieni_wyplaty CASCADE;
DROP table IF EXISTS naleznosci_za_uslugi CASCADE;
DROP table IF EXISTS historia_wyplat CASCADE;
DROP FUNCTION IF EXISTS czy_ubezpieczony (int, timestamp) CASCADE;
DROP view IF EXISTS osoby_naleznosci CASCADE;
DROP view IF EXISTS ubezpieczenia_pracownicy CASCADE;
DROP FUNCTION IF EXISTS czy_ma_umowe (bigint, timestamp) CASCADE;
DROP view IF EXISTS uslugodawcy_uslugi CASCADE;
DROP view IF EXISTS personel_medyczny_dane CASCADE;
DROP view IF EXISTS personel_medyczny_specjalizacje CASCADE;
DROP view IF EXISTS choroby_osob CASCADE;
DROP view IF EXISTS recepty_koszt CASCADE;
DROP view IF EXISTS recepty_refundacja CASCADE;
DROP view IF EXISTS personel_medyczny_leki CASCADE;
DROP FUNCTION IF EXISTS pesel_trigger () CASCADE;
DROP TRIGGER IF EXISTS pesel_check ON osoby CASCADE;
